language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t bhushan2005/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bhushan2005/react-test npm test

after_success:
  - docker build -t bhushan2005/multi-client ./client
  - docker build -t bhushan2005/multi-nginx ./nginx
  - docker build -t bhushan2005/multi-server ./server
  - docker build -t bhushan2005/multi-worker ./worker
